[package]
name = "captures-capture"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
image.workspace = true
serde.workspace = true
thiserror.workspace = true
xcap = "0.9.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-graphics = "0.25"

[lints]
workspace = true
