/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAccountMeRouteImport } from './routes/api/account/me'
import { Route as ApiUpdatesPreviewRouteImport } from './routes/api/updates/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountMeRoute = ApiAccountMeRouteImport.update({
  id: '/api/account/me',
  path: '/api/account/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdatesPreviewRoute = ApiUpdatesPreviewRouteImport.update({
  id: '/api/updates/preview',
  path: '/api/updates/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/updates/preview': typeof ApiUpdatesPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/updates/preview': typeof ApiUpdatesPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/updates/preview': typeof ApiUpdatesPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/api/feedback'
    | '/api/health'
    | '/api/account/me'
    | '/api/updates/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/api/feedback'
    | '/api/health'
    | '/api/account/me'
    | '/api/updates/preview'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/api/feedback'
    | '/api/health'
    | '/api/account/me'
    | '/api/updates/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAccountMeRoute: typeof ApiAccountMeRoute
  ApiUpdatesPreviewRoute: typeof ApiUpdatesPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/me': {
      id: '/api/account/me'
      path: '/api/account/me'
      fullPath: '/api/account/me'
      preLoaderRoute: typeof ApiAccountMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/updates/preview': {
      id: '/api/updates/preview'
      path: '/api/updates/preview'
      fullPath: '/api/updates/preview'
      preLoaderRoute: typeof ApiUpdatesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAccountMeRoute: ApiAccountMeRoute,
  ApiUpdatesPreviewRoute: ApiUpdatesPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
