[package]
name = "captures-macos-window"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
dispatch2 = "0.3"
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = [
    "std",
    "block2",
    "NSApplication",
    "NSBezierPath",
    "NSColor",
    "NSCursor",
    "NSEvent",
    "NSGraphics",
    "NSGraphicsContext",
    "NSImage",
    "NSPanel",
    "NSPasteboard",
    "NSResponder",
    "NSRunningApplication",
    "NSScreen",
    "NSTrackingArea",
    "NSView",
    "NSWindow",
    "NSWorkspace",
    "objc2-core-foundation",
] }
objc2-foundation = { version = "0.3", default-features = false, features = [
    "std",
    "NSData",
    "NSDictionary",
    "NSGeometry",
    "NSNotification",
    "NSOperation",
    "NSProcessInfo",
    "NSValue",
] }
tauri = { version = "2", default-features = false, features = ["wry"] }
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", rev = "a3122e894383aa068ec5365a42994e3ac94ba1b6" }
libc = "0.2"

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "allow", priority = -1 }
